# docker-compose.yml
version: '3.8'

services:
  frontend:
    build:
      context: ./Frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./Backend
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5433/myapp

  db:
    image: postgres:16
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nodeapp
    ports:
      - "5433:5433"

volumes:
  db-data:
